# Generated by Django 5.0.6 on 2024-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
